---
# Source: promscale/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: promscale
  namespace: default
  labels:
    app: promscale
    chart: promscale-0.7.0
    release: promscale
    heritage: Helm
---
# Source: promscale/templates/secret-connection.yaml
apiVersion: v1
kind: Secret
metadata:
  name: promscale
  namespace: default
  labels:
    app: promscale
    chart: promscale-0.7.0
    release: promscale
    heritage: Helm
stringData:
  PROMSCALE_DB_PORT: "5432"
  PROMSCALE_DB_USER: "postgres"
  PROMSCALE_DB_PASSWORD: ""
  PROMSCALE_DB_HOST: "timescaledb.default.svc.cluster.local"
  PROMSCALE_DB_NAME: "timescale"
  PROMSCALE_DB_SSL_MODE: "require"
---
# Source: promscale/templates/svc-promscale.yaml
apiVersion: v1
kind: Service
metadata:
  name: promscale-connector
  namespace: default
  labels:
    app: promscale
    chart: promscale-0.7.0
    release: promscale
    heritage: Helm
spec:
  selector:
    app: promscale
  type: ClusterIP
  ports:
  - name: metrics-port
    port: 9201
    protocol: TCP
---
# Source: promscale/templates/deployment-promscale.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: promscale
  namespace: default
  labels:
    app: promscale
    chart: promscale-0.7.0
    release: promscale
    heritage: Helm
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: promscale
  template:
    metadata:
      labels:
        app: promscale
      annotations: 
        checksum/config: 88c801c7dcedfa1badfb9c718a5de2a2e4bacb8ba3126b7b43fc40ab0b356fc4
        prometheus.io/path: /metrics
        prometheus.io/port: "9201"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - image: timescale/promscale
          imagePullPolicy: IfNotPresent
          name: promscale-connector
          envFrom:
          - secretRef:
              name: promscale
          ports:
            - containerPort: 9201
              name: metrics-port
      serviceAccountName: promscale
