apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "promscale.fullname" . }}
  namespace: {{ template "promscale.namespace" . }}
  labels:
    app: {{ template "promscale.fullname" . }}
    chart: {{ template "promscale.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.upgradeStrategy }}
  selector:
    matchLabels:
      app: {{ template "promscale.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "promscale.fullname" . }}
      {{- if .Values.prometheus.enabled }}
      annotations: 
        checksum/config: {{ printf "%s" .Values.connection | sha256sum -}}
        {{ .Values.prometheus.annotations | toYaml | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: promscale-connector
          {{- if .Values.args }}
          args:
            {{- range .Values.args }}
              - {{ . }}
            {{- end }}
          {{- end}}
          envFrom:
          - secretRef:
              {{- $secretName := ternary (include "promscale.fullname" .) .Values.connectionSecretName (eq .Values.connectionSecretName "") }}
              name: {{ $secretName }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 9201
              name: metrics-port
          {{ if .Values.tracing.enabled }}
            - containerPort: 9202
              name: traces-port
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 2 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
