{{ if eq .Values.connectionSecretName "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "promscale.fullname" . }}
  namespace: {{ template "promscale.namespace" . }}
  labels:
    app: {{ template "promscale.fullname" . }}
    chart: {{ template "promscale.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- if ne .Values.connection.uri "" }}
  PROMSCALE_DB_URI: {{ .Values.connection.uri }}
  {{- else }}
  PROMSCALE_DB_PORT: {{ .Values.connection.port | quote }}
  PROMSCALE_DB_USER: {{ .Values.connection.user }}
  PROMSCALE_DB_PASSWORD: {{ .Values.connection.password }}
  PROMSCALE_DB_HOST: {{ .Values.connection.host }}
  PROMSCALE_DB_NAME: {{ .Values.connection.dbName }}
  PROMSCALE_DB_SSL_MODE: {{ .Values.connection.sslMode }}
  {{- end }}
{{ end }}