apiVersion: v1
kind: Service
metadata:
  name: {{ include "promscale.fullname" . | trunc 53 }}-connector
  namespace: {{ template "promscale.namespace" . }}
  labels:
    app: {{ template "promscale.fullname" . }}
    chart: {{ template "promscale.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{ .Values.service.annotations | toYaml | indent 4 }}
spec:
  selector:
    app: {{ template "promscale.fullname" . }}
  type: {{ .Values.service.type }}
  ports:
  - name: metrics-port
    port: {{ .Values.prometheus.port }}
    protocol: TCP
  {{ if .Values.tracing.enabled }}
  - name: traces-port
    port: {{ .Values.tracing.port }}
    protocol: TCP
  {{- end }}
